import Head from "next/head";
import { Provider } from "react-redux";

import "../styles/globals.css";
import { wrapper } from "../store/store";

import Header from "../components/header";

function MyApp({ Component, pageProps, ...rest }) {
  const { store, props } = wrapper.useWrappedStore(rest);
  return (
    <>
      <Provider store={store}>
        <Head>
          <title>Switch</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
          <Header />
          <Component {...pageProps} />
        </>
      </Provider>
    </>
  );
}

export default MyApp;
