import Head from "next/head";
import { Provider } from "react-redux";

import "../styles/globals.css";
import store from "../store/configureStore";
import Header from "../components/header";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Switch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Provider store={store}>
          <Header />
          <Component {...pageProps} />
        </Provider>
      </>
    </>
  );
}

export default MyApp;
