import Head from "next/head";
import "../styles/globals.css";

import Header from "../components/header";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Switch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Component {...pageProps} />
      </>
    </>
  );
}

export default MyApp;
